[package]
name = "ustd"
version = "0.0.0"
edition = "2021"
authors = ["Alexey Gerasev <alexey.gerasev@gmail.com>"]

description = "Micro stdlib"
documentation = "https://docs.rs/ustd"
homepage = "https://github.com/agerasev/ustd-rs"
repository = "https://github.com/agerasev/ustd-rs.git"
readme = "README.md"
categories = ["os", "embedded", "no-std"]
keywords = ["std", "stdlib", "embedded"]
license = "MIT/Apache-2.0"

[lib]
path = "src/lib.rs"

[[bin]]
name = "main"
path = "src/main.rs"

[features]
default = ["backend-freertos"]
backend-std = ["fnv"]
backend-freertos = ["freertos", "freertos-cargo-build"]

[dependencies]
fnv = { version = "1.0.7", optional = true, default-features = false }
freertos = { package = "freertos-rust", path = "freertos-rust/freertos-rust", optional = true }

[build-dependencies]
freertos-cargo-build = { path = "freertos-rust/freertos-cargo-build", optional = true }

[dev-dependencies]
lazy_static = { version = "1.4.0", default-features = false, features = [
    "spin_no_std",
] }
