on: [push, pull_request]

jobs:
  build_and_test:
    name: ustd-rs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: bash test.sh
